"""
A set of unit tests utility functions/constants.
"""
# Http request headers;
HTTP_REQUEST_HEADER_ACCEPT = 'Accept'
HTTP_REQUEST_HEADER_ACCEPT_LANGUAGE = 'Accept-Language'


# Http verbs;
HTTP_VERB_HEAD = 'HEAD'
HTTP_VERB_GET = 'GET'
HTTP_VERB_POST = 'POST'
HTTP_VERB_DELETE = 'DELETE'
HTTP_VERB_PUT = 'PUT'
HTTP_VERB_TRACE = 'TRACE'
HTTP_VERB_CONNECT = 'CONNECT'
HTTP_VERB_OPTIONS = 'OPTIONS'


# Http response codes;
HTTP_RESPONSE_SUCCESS = 200
HTTP_RESPONSE_BAD_REQUEST = 400
HTTP_RESPONSE_NOT_FOUND = 404
HTTP_RESPONSE_NOT_ALLOWED = 405
HTTP_RESPONSE_NOT_ACCEPTABLE = 406
HTTP_RESPONSE_UNSUPPORTED_MEDIA_TYPE = 415
HTTP_RESPONSE_INTERNAL_SERVER_ERROR = 500


# Some media types of interest.
HTTP_MEDIA_TYPE_JSON = 'application/json'
HTTP_MEDIA_TYPE_XML = 'application/xml'
HTTP_MEDIA_TYPE_BASE64 = 'application/base64'





